

export type FeatureShow = 
 
    "PRIVATE" |
    "PRIVATE_AND_RECRUITERS" |
    "DIRECT_CONNECTIONS" |
    "DIRECT_CONNECTIONS_AND_RECRUITERS" |
    "FOLLOWERS" |
    "FOLLOWERS_AND_RECRUITERS" |
    "PUBLIC"
    ;

export const featureShowList: FeatureShow[] = [
    "PRIVATE",
    "PRIVATE_AND_RECRUITERS",
    "DIRECT_CONNECTIONS",
    "DIRECT_CONNECTIONS_AND_RECRUITERS",
    "FOLLOWERS",
    "FOLLOWERS_AND_RECRUITERS",
    "PUBLIC"
];